const CMS_BASE='https://img.cms.kanjian.com/frontpage/v5/home/release/dsps/';
const RAW='https://raw.githubusercontent.com/zeroooolu/music-promotion/main/frontend/star-release/assets/platform-logos/';
const namedLogos={
  'Spotify':RAW+'spotify.jpeg','Apple Music':RAW+'apple-music.jpg','QQ音乐':RAW+'qq-music.png','网易云音乐':RAW+'netease-music.jpg','酷狗音乐':RAW+'kugou-music.png','酷我音乐':RAW+'kuwo-music.png','汽水音乐':RAW+'douyin-qishui.jpg','华为音乐':RAW+'huawei-music.jpg','Amazon Music':RAW+'amazon-music.png','YouTube Music':RAW+'youtube-music.jpg','TikTok':RAW+'tiktok.jpeg','KKBOX':RAW+'kkbox.png','JOOX':RAW+'joox.png'
};
const shortName=n=>({Spotify:'SP','Apple Music':'AM','QQ音乐':'QQ','网易云音乐':'网易','酷狗音乐':'酷狗','酷我音乐':'酷我','汽水音乐':'汽水','华为音乐':'华为','Amazon Music':'AZ','YouTube Music':'YT',TikTok:'TT',TIDAL:'TD',Deezer:'DZ',Beatport:'BP',Qobuz:'QZ'}[n]||String(n).slice(0,2));

function imageMarkup(name){const url=namedLogos[name];return url?`<img src="${url}" alt="${name}" loading="lazy" referrerpolicy="no-referrer">`:shortName(name)}
function addImgFallback(scope=document){scope.querySelectorAll('img').forEach(img=>{if(img.dataset.fallbackBound)return;img.dataset.fallbackBound='1';img.addEventListener('error',()=>{const p=img.parentElement;if(!p)return;p.classList.add('logo-failed');p.dataset.fallback=shortName(img.alt||'DSP');img.remove()})})}
function buildMarquee(){document.querySelectorAll('[data-dsp-marquee]').forEach(el=>{if(el.children.length)return;const ids=[...Array(25)].map((_,i)=>i+1);el.innerHTML=[...ids,...ids].map(i=>`<div class="logo-box" data-fallback="DSP"><img src="${CMS_BASE}${i}.png" alt="合作发行平台" loading="lazy" referrerpolicy="no-referrer"></div>`).join('')});addImgFallback()}
function hydrateNamedLogos(){document.querySelectorAll('[data-logo]').forEach(el=>{const name=el.dataset.logo;el.dataset.fallback=shortName(name);el.innerHTML=imageMarkup(name)});addImgFallback()}

function initBilling(){const buttons=[...document.querySelectorAll('[data-billing]')];if(!buttons.length)return;const prices={monthly:{china:'29.9',global:'59.9',chinaUnit:'/月',globalUnit:'/月'},annual:{china:'299',global:'599',chinaUnit:'/年',globalUnit:'/年'}};buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const p=prices[btn.dataset.billing];document.querySelector('[data-price-china]').textContent='¥'+p.china;document.querySelector('[data-unit-china]').textContent=p.chinaUnit;document.querySelector('[data-price-global]').textContent='¥'+p.global;document.querySelector('[data-unit-global]').textContent=p.globalUnit;document.querySelectorAll('[data-billing-note]').forEach(n=>n.textContent=btn.dataset.billing==='monthly'?'按月支付，适合更灵活地管理发行预算':'一次支付全年，价格更优惠') }))}
function initEstimator(){const tracks=document.querySelector('[data-track-count]'),channels=document.querySelector('[data-channel-count]');if(!tracks||!channels)return;let t=5,c=6;const refresh=()=>{tracks.textContent=t;channels.textContent=c;const e=document.querySelector('[data-estimate]');if(e)e.textContent='¥'+t*c};document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{const x=b.dataset.step;if(x==='track-up')t=Math.min(200,t+1);if(x==='track-down')t=Math.max(1,t-1);if(x==='channel-up')c=Math.min(25,c+1);if(x==='channel-down')c=Math.max(1,c-1);refresh()}));refresh()}

const channelData=[
{name:'QQ音乐',region:'cn',status:'可发行 · AI 内容需声明；部分 AI 内容收益和推荐受限',logo:'QQ音乐'},
{name:'网易云音乐',region:'cn',status:'可发行 · AI 内容可能被平台标识',logo:'网易云音乐'},
{name:'酷狗音乐',region:'cn',status:'可发行 · AI 内容遵循 TME 规则',logo:'酷狗音乐'},
{name:'酷我音乐',region:'cn',status:'可发行 · AI 内容遵循 TME 规则',logo:'酷我音乐'},
{name:'汽水音乐',region:'cn',status:'可发行 · 高相似度内容可能被限制',logo:'汽水音乐'},
{name:'华为音乐',region:'cn',status:'可发行',logo:'华为音乐'},
{name:'Spotify',region:'global',status:'可发行 · 部分 AI Persona 的推荐资格可能受限',logo:'Spotify'},
{name:'Apple Music',region:'global',status:'可发行 · 支持提交 AI 透明度信息',logo:'Apple Music'},
{name:'Amazon Music',region:'global',status:'可发行 · AI 细则持续确认',logo:'Amazon Music'},
{name:'YouTube Music',region:'global',status:'可发行 · 支持生成式 AI 标记',logo:'YouTube Music'},
{name:'TikTok',region:'global',status:'可发行 · 平台供给规则持续确认',logo:'TikTok'},
{name:'TIDAL',region:'global',status:'可发行 · 100% AI 录音不参与版税',logo:null,warning:true},
{name:'Deezer',region:'global',status:'可发行 · 纯 AI 内容不进入推荐',logo:null,warning:true},
{name:'Beatport',region:'global',status:'完全或主要由 AI 生成的音乐当前不可发行',logo:null,blockedAI:true},
{name:'Qobuz',region:'global',status:'100% AI 内容当前不可新发行',logo:null,blockedAI:true}
];

function initReleaseBuilder(){const root=document.querySelector('[data-release-builder]');if(!root)return;let aiMode='assisted',region='all',term=1;let selected=new Set(channelData.filter(c=>!c.blockedAI).slice(0,10).map(c=>c.name));const list=document.querySelector('[data-channels]');const render=()=>{const filtered=channelData.filter(c=>region==='all'||c.region===region);list.innerHTML=filtered.map(c=>{const disabled=aiMode==='full'&&c.blockedAI;if(disabled)selected.delete(c.name);const sel=selected.has(c.name)&&!disabled;return `<div class="channel ${sel?'selected':''} ${disabled?'disabled':''}" data-channel="${c.name}"><div class="channel-logo" ${c.logo?`data-logo="${c.logo}"`:''} data-fallback="${shortName(c.name)}">${c.logo?'':shortName(c.name)}</div><div><strong>${c.name}</strong><small>${disabled?'当前这类作品不能发行到该平台':c.status}</small></div><div class="check">✓</div></div>`}).join('');hydrateNamedLogos();document.querySelectorAll('[data-channel]').forEach(el=>el.addEventListener('click',()=>{if(el.classList.contains('disabled'))return;const n=el.dataset.channel;selected.has(n)?selected.delete(n):selected.add(n);render()}));document.querySelector('[data-selected-count]').textContent=selected.size;document.querySelector('[data-summary-channels]').textContent=selected.size+' 个';document.querySelector('[data-summary-term]').textContent=term+' 年';document.querySelector('[data-summary-total]').innerHTML='¥'+selected.size*term+'<span> / 本次</span>';const available=channelData.filter(c=>!(aiMode==='full'&&c.blockedAI)).length;const rec=document.querySelector('[data-sub-recommend]');if(rec)rec.innerHTML=selected.size>=10?`<div class="top"><strong>经常发行？订阅可能更划算</strong><span class="tag">可选</span></div><p>全球发行订阅最多覆盖 50 首当前在架歌曲；这首歌目前有 ${available} 个已接入平台可以选择。</p>`:`<div class="top"><strong>这次按量发行更合适</strong><span class="tag">按实际使用付费</span></div><p>你只选择了 ${selected.size} 个平台，只需要为实际使用的平台付费。</p>`};document.querySelectorAll('[data-ai-mode]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-ai-mode]').forEach(x=>x.classList.remove('active'));el.classList.add('active');aiMode=el.dataset.aiMode;if(aiMode!=='full')channelData.filter(c=>c.blockedAI).forEach(c=>selected.add(c.name));render()}));document.querySelectorAll('[data-region]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-region]').forEach(x=>x.classList.remove('active'));el.classList.add('active');region=el.dataset.region;render()}));document.querySelectorAll('[data-term]').forEach(el=>el.addEventListener('click',()=>{document.querySelectorAll('[data-term]').forEach(x=>x.classList.remove('active'));el.classList.add('active');term=Number(el.dataset.term);render()}));render()}

document.addEventListener('DOMContentLoaded',()=>{buildMarquee();hydrateNamedLogos();initBilling();initEstimator();initReleaseBuilder()});